/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/Navigation/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/Navigation/AppHeader.vue')['default']
    Home: typeof import('./src/components/Home/Home.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    LoginView: typeof import('./src/components/Login/LoginView.vue')['default']
    Menu: typeof import('./src/components/Navigation/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkingTime: typeof import('./src/components/store/workingTime.vue')['default']
  }
}
